Config = {}

Config['Items'] = {
    {
        itemName = 'wheel',
        itemLabel = 'Rueda vehiculo',
        objName = 'prop_wheel_03',
        anim = 'anim@heists@box_carry@',
        bone = 57005,
        weight = 1,
        posX = 0.05,
        posY = 0.25,
        posZ = -0.3,
        rotX = 300.0,
        rotY = 250.0,
        rotZ = 20.0,
    },
    {
        itemName = 'glass',
        itemLabel = 'Cristal vehiculo',
        objName = 'prop_cs_cardbox_01',
        anim = 'anim@heists@box_carry@',
        bone = 57005,
        weight = 1,
        posX = 0.05,
        posY =  0.07,
        posZ = -0.28,
        rotX = 300.0,
        rotY = 250.0,
        rotZ = 10.0,
    },    
    {
        itemName = 'door',
        itemLabel = 'Puerta vehículo',
        objName = 'prop_car_door_01',
        anim = 'anim@heists@box_carry@',
        bone = 57005,
        weight = 1,
        posX = 0.4,
        posY = -0.5,
        posZ = -0.3,
        rotX = 250.0,
        rotY = 96.0,
        rotZ = 10.0,
    },
    {
        itemName = 'battery',
        itemLabel = 'Bateria',
        objName = 'prop_battery_02',
        anim = 'anim@heists@narcotics@trash',
        bone = 57005,
        weight = 1,
        posX = 0.1,
        posY = 0.05,
        posZ = -0.15,
        rotX = 300.0,
        rotY = 250.0,
        rotZ = 20.0,
    },
    {
        itemName = 'balleta',
        itemLabel = 'Esponja',
        objName = 'prop_sponge_01',
        bone = 57005,
        anim = 'anim@heists@narcotics@trash',
        weight = 1,
        posX = 0.1,
        posY = -0.02,
        posZ = -0.09,
        rotX = 250.0,
        rotY = 250.0,
        rotZ = 20.0,
    },
    {
        itemName = 'notepad',
        itemLabel = 'Bloc de Notas',
        objName = 'prop_notepad_02',
        bone = 57005,
        anim = false,
        weight = 1,
        posX = 0.1,
        posY = -0.02,
        posZ = -0.05,
        rotX = 300.0,
        rotY = 210.0,
        rotZ = 30.0,
    },
}